### ISSUE TITLE
Second meeting

### ISSUE THREAD

**Issue by flackr** [web-platform-tests/interop-2022-pointer#6]
Scheduling the followup to #3. At this meeting I propose:

1. Review the state of the [spreadsheet](https://docs.google.com/spreadsheets/d/1K3lnen0hP0T3z7lDmUnTtTrA-qWJ5JVTvkuvhV8AQhY/edit#gid=0). Final call for additional issues.
2. Determine breakdown of work and plan of action to begin completing the above items.
3. Plan for subsequent check-in

**Comment by foolip** [comment]
@flackr is there a date for this meeting yet?

**Comment by mustaqahmed** [comment]
Done going through all Hotlist=Interop input bugs in Chromium: added the missing ones into the [spreadsheet](https://docs.google.com/spreadsheets/d/1K3lnen0hP0T3z7lDmUnTtTrA-qWJ5JVTvkuvhV8AQhY/edit?usp=sharing), and deduped/updated existing entries.

**Comment by flackr** [comment]
> @flackr is there a date for this meeting yet?

Scheduled the meeting for Sept 21 at 16 UTC based on form responses.

I've also gone through our react issue list and added the relevant issues (ensuring they weren't already covered).

**Comment by flackr** [comment]
We just had our second meeting. The following is an approximate summary, please add details if I've missed anything:

Attendees: @flackr @mustaqahmed @smaug---- @zcorpan @EdgarChen

1. Review the state of the [spreadsheet](https://docs.google.com/spreadsheets/d/1K3lnen0hP0T3z7lDmUnTtTrA-qWJ5JVTvkuvhV8AQhY/edit#gid=0). Final call for additional issues.

   Current state is most issues are clear but don't have tests. There are a handful of unclear issues, and some are likely untestable

   The triaged checkboxes don't reflect new expected outcome state. They predate the yellow boxes. In the meeting we unchecked those which do not have yellow boxes completed yet and will use these to mark output state completion.
 
2. Determine breakdown of work and plan of action to begin completing the above items.

   Proposal:
   * Reset all triaged checkboxes
   * People set owner to take on a line
   * Check the boxes according to expectation
      * included / excluded in interop 2023
      * Obvious expected behavior
      * Spec exists for expected behavior
      * Automated WPT test exists - WPT field should have a query that can be used on wpt.fyi so we have a consistent field format that we can join to make a wpt.fyi query.
         * If a test does not exist we need to land a test.
         * Manual tests can be linked but not check the checkbox. Ideally file issue in wpt with type:untestable and add that issue in the wpt link
   * Once finished all of the above, check triaged

   How can we handle issues with compat concerns?
   - This is likely not something we can resolve here but should push on ensuring that spec issues are filed and discussion happens on those.

   What about duplicates?
   - Talk to other owner if exists (perhaps use chat)
   - Delete row and make other description more generic

3. Plan for subsequent check-in
   Overall timeline
   - Proposal in next few weeks with expectation that tests will be ready soon
   - Get all tests in by beginning of December for focus area consideration
   - Check in end of October
   - AI: @flackr to send reminder in 3 weeks to go through list

   Deep dive areas?
   - e.g. disabled form controls has compat concerns
   - TouchEvent exposed on non-touch devices?
   
   Not clear that we can resolve these issues in our group. We should try to push on the relevant spec discussions. One output from the investigation area may be a list of areas that we don't know what the expectation should be (and similarly, a list of things we can't test).
